import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar";
import Footer from "../components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon"  type="image/png" href="/favicon.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-[#181A1B] text-gray-200 flex flex-col`}>
        <NavBar />
        <main className="flex-1 flex flex-col items-center justify-center w-full px-4 sm:px-6 md:px-8">
          <div className="w-full max-w-screen-lg">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
